// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvhAIk0v3TVIR_fTxSmUxw370p_NHTf1A',
    appId: '1:595622564213:web:aa12b39b6ca10afb19833c',
    messagingSenderId: '595622564213',
    projectId: 'mynotes1-46f42',
    authDomain: 'mynotes1-46f42.firebaseapp.com',
    storageBucket: 'mynotes1-46f42.firebasestorage.app',
    measurementId: 'G-H4SSTXKGEP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3RoIxGOgOewaCzSr5Uori8pPIrxxAjX4',
    appId: '1:595622564213:android:230ad4e4b8bd823619833c',
    messagingSenderId: '595622564213',
    projectId: 'mynotes1-46f42',
    storageBucket: 'mynotes1-46f42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDktjXY98BPdfrcYBC7Xd6QvjKjWF80I6I',
    appId: '1:595622564213:ios:e7af48882a83df7d19833c',
    messagingSenderId: '595622564213',
    projectId: 'mynotes1-46f42',
    storageBucket: 'mynotes1-46f42.firebasestorage.app',
    iosBundleId: 'com.example.chatgpt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDktjXY98BPdfrcYBC7Xd6QvjKjWF80I6I',
    appId: '1:595622564213:ios:e7af48882a83df7d19833c',
    messagingSenderId: '595622564213',
    projectId: 'mynotes1-46f42',
    storageBucket: 'mynotes1-46f42.firebasestorage.app',
    iosBundleId: 'com.example.chatgpt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvhAIk0v3TVIR_fTxSmUxw370p_NHTf1A',
    appId: '1:595622564213:web:e7762a41ae75422619833c',
    messagingSenderId: '595622564213',
    projectId: 'mynotes1-46f42',
    authDomain: 'mynotes1-46f42.firebaseapp.com',
    storageBucket: 'mynotes1-46f42.firebasestorage.app',
    measurementId: 'G-QPT13SS0BY',
  );
}
